"""
This is a setup.py script generated by py2applet
Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ethBar.py']
DATA_FILES = []
OPTIONS = {
  'argv_emulation': True,  
  'plist': {
    'LSUIElement': True,
  },
  'packages': ['rumps', 'requests']
}

setup(
    name='ethBar',
    version='0.0.2',
    author='dylandesrosier',
    author_email='dylandesrosier@gmail.com',
    description='MacOS StatusBar Ticker for cryptocurrencies like Ethereum',
    license='MIT',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
